[[headers]]
for = "/*"

[headers.values]
Link = '''
<https://unpkg.com>; rel="preconnect",
<https://quiz.bearcat.dev>; rel="preconnect"
'''

[[redirects]]
from = "https://wizardly-bose-3ca792.netlify.app/*"
to = "https://digitalfair.kthfoodtech.se/:splat"
force = true
status = 301
